# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Sopt-iOS-assignment-MVVM' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Sopt-iOS-assignment-MVVM

  target 'Sopt-iOS-assignment-MVVMTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Sopt-iOS-assignment-MVVMUITests' do
    # Pods for testing
  end

end
